apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: en0gskus9-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: en0gskus9-go 
  name: en0gskus9-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: en0gskus9-go 
